// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bveucrmlqqvgrwbsqoht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZXVjcm1scXF2Z3J3YnNxb2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTEwNTQsImV4cCI6MjA2NTk4NzA1NH0.BroSmG1TnmCY8fl97YlNePCEmhH5sbNxNNRAcWe-iTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);